"""empty message

Revision ID: e572c79a7a4e
Revises: 
Create Date: 2020-08-31 19:03:33.315960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e572c79a7a4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_fantasia', sa.String(), nullable=False),
    sa.Column('razon_social', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.Column('productor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['productor_id'], ['productores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productor_producto',
    sa.Column('productor_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['productor_id'], ['productores.id'], )
    )
    op.create_table('rubro_producto',
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubros.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rubro_producto')
    op.drop_table('productor_producto')
    op.drop_table('imagenes')
    op.drop_table('rubros')
    op.drop_table('productos')
    op.drop_table('productores')
    # ### end Alembic commands ###
